from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Location

if TYPE_CHECKING:
    from .world import ReplayleeWorld

HT_ID = 00000
TT_ID = 10000
GL_ID = 20000
MM_ID = 30000
CC_ID = 40000
GA_ID = 50000
QUILL_ID = 00000
PAGIE_ID = 1000
SHOP_ID = 2000
CASINO_TOKEN_ID = 3000
LOCATION_NAME_TO_ID = {
    # Trowzer shop purchases (Quillsanity only). Item indices 0-5 map to Shop 1-6.
    # Hivory Towers Pagies
    "HT - Contents": HT_ID + PAGIE_ID + 0,
    "HT - Bunged Up Buddy": HT_ID + PAGIE_ID + 1,
    "HT - Butterfright!": HT_ID + PAGIE_ID + 2,
    "HT - Mastered": HT_ID + PAGIE_ID + 3,
    "HT - Bonanza Bridge": HT_ID + PAGIE_ID + 4,
    "HT - Gold Standard": HT_ID + PAGIE_ID + 5,
    "HT - Firefighter": HT_ID + PAGIE_ID + 6,
    "HT - P.A.G.I.E": HT_ID + PAGIE_ID + 7,
    "HT - Pipe Panes": HT_ID + PAGIE_ID + 8,
    "HT - Sunken Salvage": HT_ID + PAGIE_ID + 9,
    "HT - Briney Box": HT_ID + PAGIE_ID + 10,
    "HT - Maestro Managed": HT_ID + PAGIE_ID + 11,
    "HT - Camera Shy": HT_ID + PAGIE_ID + 12,
    "HT - Aquatic Circuit": HT_ID + PAGIE_ID + 13,
    "HT - Secret Shelves": HT_ID + PAGIE_ID + 14,
    "HT - Fixer Upper": HT_ID + PAGIE_ID + 15,
    "HT - Plumbing Plunder": HT_ID + PAGIE_ID + 16,
    "HT - Busted Barrel": HT_ID + PAGIE_ID + 17,
    "HT - Picture Perfect": HT_ID + PAGIE_ID + 18,
    # "HT - Picture Perfect 2": HT_ID + PAGIE_ID + 19,
    "HT - Treasure Trouble": HT_ID + PAGIE_ID + 20,
    "HT - Blasting Block": HT_ID + PAGIE_ID + 21,
    "HT - Curious Cap": HT_ID + PAGIE_ID + 22,
    "HT - Shrubbery Sneak": HT_ID + PAGIE_ID + 23,
    "HT - Cool and Collected": HT_ID + PAGIE_ID + 24,
    "HT - Downwards Dash": HT_ID + PAGIE_ID + 25,
    "HT - Rextro (Bronze)": HT_ID + PAGIE_ID + 26,
    "HT - Rextro (Silver)": HT_ID + PAGIE_ID + 27,
    "HT - Rextro (Gold)": HT_ID + PAGIE_ID + 28,
    # "HT - Bite'n Switch Blizzard (Bronze)": HT_ID + PAGIE_ID + 29,
    # "HT - Bite'n Switch Blizzard (Silver)": HT_ID + PAGIE_ID + 30,
    # "HT - Bite'n Switch Blizzard (Gold)": HT_ID + PAGIE_ID + 31,
    # "HT - Hot Hop Hike(Bronze)": HT_ID + PAGIE_ID + 32,
    # "HT - Hot Hop Hike (Silver)": HT_ID + PAGIE_ID + 33,
    # "HT - Hot Hop Hike (Gold)": HT_ID + PAGIE_ID + 34,
    "HT - Wind Test": HT_ID + PAGIE_ID + 35,
    "HT - Slide Ride": HT_ID + PAGIE_ID + 36,
    "HT - Coineleus' Climb": HT_ID + PAGIE_ID + 37,
    "HT - Page Turner": HT_ID + PAGIE_ID + 38,
    "HT - Booksmart": HT_ID + PAGIE_ID + 39,
    "HT - Head Case": HT_ID + PAGIE_ID + 40,
    "HT - Teed Off!": HT_ID + PAGIE_ID + 41,
    "HT - Sentry Skipper": HT_ID + PAGIE_ID + 42,
    "HT - Container Tower": HT_ID + PAGIE_ID + 43,
    "HT - Poison Protection": HT_ID + PAGIE_ID + 44,
    "HT - Rocky Rumble": HT_ID + PAGIE_ID + 45,
    "HT - Toppled Tomes": HT_ID + PAGIE_ID + 46,
    "HT - Capital Beaten": HT_ID + PAGIE_ID + 47,
    
    # Tribalstack Tropics - Quills
    "TT - Quill 0": TT_ID + QUILL_ID + 0,
    "TT - Quill 1": TT_ID + QUILL_ID + 1,
    "TT - Quill 2": TT_ID + QUILL_ID + 2,
    "TT - Quill 3": TT_ID + QUILL_ID + 3,
    "TT - Quill 4": TT_ID + QUILL_ID + 4,
    "TT - Quill 5": TT_ID + QUILL_ID + 5,
    "TT - Quill 6": TT_ID + QUILL_ID + 6,
    "TT - Quill 7": TT_ID + QUILL_ID + 7,
    "TT - Quill 8": TT_ID + QUILL_ID + 8,
    "TT - Quill 9": TT_ID + QUILL_ID + 9,
    "TT - Quill 10": TT_ID + QUILL_ID + 10,
    "TT - Quill 11": TT_ID + QUILL_ID + 11,
    "TT - Quill 12": TT_ID + QUILL_ID + 12,
    "TT - Quill 13": TT_ID + QUILL_ID + 13,
    "TT - Quill 14": TT_ID + QUILL_ID + 14,
    "TT - Quill 15": TT_ID + QUILL_ID + 15,
    "TT - Quill 16": TT_ID + QUILL_ID + 16,
    "TT - Quill 17": TT_ID + QUILL_ID + 17,
    "TT - Quill 18": TT_ID + QUILL_ID + 18,
    "TT - Quill 19": TT_ID + QUILL_ID + 19,
    "TT - Quill 20": TT_ID + QUILL_ID + 20,
    "TT - Quill 21": TT_ID + QUILL_ID + 21,
    "TT - Quill 22": TT_ID + QUILL_ID + 22,
    "TT - Quill 23": TT_ID + QUILL_ID + 23,
    "TT - Quill 24": TT_ID + QUILL_ID + 24,
    "TT - Quill 25": TT_ID + QUILL_ID + 25,
    "TT - Quill 26": TT_ID + QUILL_ID + 26,
    "TT - Quill 27": TT_ID + QUILL_ID + 27,
    "TT - Quill 28": TT_ID + QUILL_ID + 28,
    "TT - Quill 29": TT_ID + QUILL_ID + 29,
    "TT - Quill 30": TT_ID + QUILL_ID + 30,
    "TT - Quill 31": TT_ID + QUILL_ID + 31,
    "TT - Quill 32": TT_ID + QUILL_ID + 32,
    "TT - Quill 33": TT_ID + QUILL_ID + 33,
    "TT - Quill 34": TT_ID + QUILL_ID + 34,
    "TT - Quill 35": TT_ID + QUILL_ID + 35,
    "TT - Quill 36": TT_ID + QUILL_ID + 36,
    "TT - Quill 37": TT_ID + QUILL_ID + 37,
    "TT - Quill 38": TT_ID + QUILL_ID + 38,
    "TT - Quill 39": TT_ID + QUILL_ID + 39,
    "TT - Quill 40": TT_ID + QUILL_ID + 40,
    "TT - Quill 41": TT_ID + QUILL_ID + 41,
    "TT - Quill 42": TT_ID + QUILL_ID + 42,
    "TT - Quill 43": TT_ID + QUILL_ID + 43,
    "TT - Quill 44": TT_ID + QUILL_ID + 44,
    "TT - Quill 45": TT_ID + QUILL_ID + 45,
    "TT - Quill 46": TT_ID + QUILL_ID + 46,
    "TT - Quill 47": TT_ID + QUILL_ID + 47,
    "TT - Quill 48": TT_ID + QUILL_ID + 48,
    "TT - Quill 49": TT_ID + QUILL_ID + 49,
    "TT - Quill 50": TT_ID + QUILL_ID + 50,
    "TT - Quill 51": TT_ID + QUILL_ID + 51,
    "TT - Quill 52": TT_ID + QUILL_ID + 52,
    "TT - Quill 53": TT_ID + QUILL_ID + 53,
    "TT - Quill 54": TT_ID + QUILL_ID + 54,
    "TT - Quill 55": TT_ID + QUILL_ID + 55,
    "TT - Quill 56": TT_ID + QUILL_ID + 56,
    "TT - Quill 57": TT_ID + QUILL_ID + 57,
    "TT - Quill 58": TT_ID + QUILL_ID + 58,
    "TT - Quill 59": TT_ID + QUILL_ID + 59,
    "TT - Quill 60": TT_ID + QUILL_ID + 60,
    "TT - Quill 61": TT_ID + QUILL_ID + 61,
    "TT - Quill 62": TT_ID + QUILL_ID + 62,
    "TT - Quill 63": TT_ID + QUILL_ID + 63,
    "TT - Quill 64": TT_ID + QUILL_ID + 64,
    "TT - Quill 65": TT_ID + QUILL_ID + 65,
    "TT - Quill 66": TT_ID + QUILL_ID + 66,
    "TT - Quill 67": TT_ID + QUILL_ID + 67,
    "TT - Quill 68": TT_ID + QUILL_ID + 68,
    "TT - Quill 69": TT_ID + QUILL_ID + 69,
    "TT - Quill 70": TT_ID + QUILL_ID + 70,
    "TT - Quill 71": TT_ID + QUILL_ID + 71,
    "TT - Quill 72": TT_ID + QUILL_ID + 72,
    "TT - Quill 73": TT_ID + QUILL_ID + 73,
    "TT - Quill 74": TT_ID + QUILL_ID + 74,
    "TT - Quill 75": TT_ID + QUILL_ID + 75,
    "TT - Quill 76": TT_ID + QUILL_ID + 76,
    "TT - Quill 77": TT_ID + QUILL_ID + 77,
    "TT - Quill 78": TT_ID + QUILL_ID + 78,
    "TT - Quill 79": TT_ID + QUILL_ID + 79,
    "TT - Quill 80": TT_ID + QUILL_ID + 80,
    "TT - Quill 81": TT_ID + QUILL_ID + 81,
    "TT - Quill 82": TT_ID + QUILL_ID + 82,
    "TT - Quill 83": TT_ID + QUILL_ID + 83,
    "TT - Quill 84": TT_ID + QUILL_ID + 84,
    "TT - Quill 85": TT_ID + QUILL_ID + 85,
    "TT - Quill 86": TT_ID + QUILL_ID + 86,
    "TT - Quill 87": TT_ID + QUILL_ID + 87,
    "TT - Quill 88": TT_ID + QUILL_ID + 88,
    "TT - Quill 89": TT_ID + QUILL_ID + 89,
    "TT - Quill 90": TT_ID + QUILL_ID + 90,
    "TT - Quill 91": TT_ID + QUILL_ID + 91,
    "TT - Quill 92": TT_ID + QUILL_ID + 92,
    "TT - Quill 93": TT_ID + QUILL_ID + 93,
    "TT - Quill 94": TT_ID + QUILL_ID + 94,
    "TT - Quill 95": TT_ID + QUILL_ID + 95,
    "TT - Quill 96": TT_ID + QUILL_ID + 96,
    "TT - Quill 97": TT_ID + QUILL_ID + 97,
    "TT - Quill 98": TT_ID + QUILL_ID + 98,
    "TT - Quill 99": TT_ID + QUILL_ID + 99,
    "TT - Quill 100": TT_ID + QUILL_ID + 100,
    "TT - Quill 101": TT_ID + QUILL_ID + 101,
    "TT - Quill 102": TT_ID + QUILL_ID + 102,
    "TT - Quill 103": TT_ID + QUILL_ID + 103,
    "TT - Quill 104": TT_ID + QUILL_ID + 104,
    "TT - Quill 105": TT_ID + QUILL_ID + 105,
    "TT - Quill 106": TT_ID + QUILL_ID + 106,
    "TT - Quill 107": TT_ID + QUILL_ID + 107,
    "TT - Quill 108": TT_ID + QUILL_ID + 108,
    "TT - Quill 109": TT_ID + QUILL_ID + 109,
    "TT - Quill 110": TT_ID + QUILL_ID + 110,
    "TT - Quill 111": TT_ID + QUILL_ID + 111,
    "TT - Quill 112": TT_ID + QUILL_ID + 112,
    "TT - Quill 113": TT_ID + QUILL_ID + 113,
    "TT - Quill 114": TT_ID + QUILL_ID + 114,
    "TT - Quill 115": TT_ID + QUILL_ID + 115,
    "TT - Quill 116": TT_ID + QUILL_ID + 116,
    "TT - Quill 117": TT_ID + QUILL_ID + 117,
    "TT - Quill 118": TT_ID + QUILL_ID + 118,
    "TT - Quill 119": TT_ID + QUILL_ID + 119,
    "TT - Quill 120": TT_ID + QUILL_ID + 120,
    "TT - Quill 121": TT_ID + QUILL_ID + 121,
    "TT - Quill 122": TT_ID + QUILL_ID + 122,
    "TT - Quill 123": TT_ID + QUILL_ID + 123,
    "TT - Quill 124": TT_ID + QUILL_ID + 124,
    "TT - Quill 125": TT_ID + QUILL_ID + 125,
    "TT - Quill 126": TT_ID + QUILL_ID + 126,
    "TT - Quill 127": TT_ID + QUILL_ID + 127,
    "TT - Quill 128": TT_ID + QUILL_ID + 128,
    "TT - Quill 129": TT_ID + QUILL_ID + 129,
    "TT - Quill 130": TT_ID + QUILL_ID + 130,
    "TT - Quill 131": TT_ID + QUILL_ID + 131,
    "TT - Quill 132": TT_ID + QUILL_ID + 132,
    "TT - Quill 133": TT_ID + QUILL_ID + 133,
    "TT - Quill 134": TT_ID + QUILL_ID + 134,
    "TT - Quill 135": TT_ID + QUILL_ID + 135,
    "TT - Quill 136": TT_ID + QUILL_ID + 136,
    "TT - Quill 137": TT_ID + QUILL_ID + 137,
    "TT - Quill 138": TT_ID + QUILL_ID + 138,
    "TT - Quill 139": TT_ID + QUILL_ID + 139,
    "TT - Quill 140": TT_ID + QUILL_ID + 140,
    "TT - Quill 141": TT_ID + QUILL_ID + 141,
    "TT - Quill 142": TT_ID + QUILL_ID + 142,
    "TT - Quill 143": TT_ID + QUILL_ID + 143,
    "TT - Quill 144": TT_ID + QUILL_ID + 144,
    "TT - Quill 145": TT_ID + QUILL_ID + 145,
    "TT - Quill 146": TT_ID + QUILL_ID + 146,
    "TT - Quill 147": TT_ID + QUILL_ID + 147,
    "TT - Quill 148": TT_ID + QUILL_ID + 148,
    "TT - Quill 149": TT_ID + QUILL_ID + 149,

        # Tribalstack Tropics - Pagies
    "TT - Cameo Quest": TT_ID + PAGIE_ID + 0,
    "TT - Idol Ascent": TT_ID + PAGIE_ID + 1,
    "TT - Hot Water": TT_ID + PAGIE_ID + 2,
    "TT - Noisy Note": TT_ID + PAGIE_ID + 3,
    "TT - Dino Score": TT_ID + PAGIE_ID + 4,
    "TT - Hidden High-jinks!": TT_ID + PAGIE_ID + 5,
    "TT - Tile Wiles": TT_ID + PAGIE_ID + 6,
    "TT - Rextro (Bronze)": TT_ID + PAGIE_ID + 7,
    "TT - Rextro (Silver)": TT_ID + PAGIE_ID + 8,
    "TT - Rextro (Gold)": TT_ID + PAGIE_ID + 9,
    "TT - Kartos (Bronze)": TT_ID + PAGIE_ID + 10,
    "TT - Kartos (Silver)": TT_ID + PAGIE_ID + 11,
    "TT - Kartos (Gold)": TT_ID + PAGIE_ID + 12,
    "TT - Sideways Shuffle": TT_ID + PAGIE_ID + 13,
    "TT - Target Time": TT_ID + PAGIE_ID + 14,
    "TT - Suspicious Summit": TT_ID + PAGIE_ID + 15,
    "TT - Feeling Thirsty": TT_ID + PAGIE_ID + 16,
    "TT - Blastooie Buddy-up": TT_ID + PAGIE_ID + 17,
    "TT - Weighting It Out": TT_ID + PAGIE_ID + 18,
    "TT - Up and Down Showdown": TT_ID + PAGIE_ID + 19,
    "TT - Basement Bother": TT_ID + PAGIE_ID + 20,
    "TT - Seeing Green": TT_ID + PAGIE_ID + 21,
    "TT - Wild Hog Chase": TT_ID + PAGIE_ID + 22,
    "TT - Get It Together": TT_ID + PAGIE_ID + 23,
    "TT - Temple Treasure": TT_ID + PAGIE_ID + 24,
    "TT - Rolling Goaling": TT_ID + PAGIE_ID + 25,
    "TT - Submerged Souvenir": TT_ID + PAGIE_ID + 26,
    "TT - Underwater Maze": TT_ID + PAGIE_ID + 27,
    # "TT - Flower Shower": TT_ID + PAGIE_ID + 28,
    "TT - Duke It Out!": TT_ID + PAGIE_ID + 29,
    "TT - Riverbed Race": TT_ID + PAGIE_ID + 30,
    "TT - Chilled Out Contest": TT_ID + PAGIE_ID + 31,
    "TT - Sonar So Good": TT_ID + PAGIE_ID + 32,
    "TT - Scorching Shuffle": TT_ID + PAGIE_ID + 33,
    "TT - Bone Idle": TT_ID + PAGIE_ID + 34,
    "TT - Soaring Success": TT_ID + PAGIE_ID + 35,
    "TT - Collect all the Quills": TT_ID + PAGIE_ID + 36,
    # "TT - 4 Pagie Pieces": TT_ID + PAGIE_ID + 37,
    # "TT - 4 More Pagie Pieces": TT_ID + PAGIE_ID + 38,
    # "TT - Normy Nabbed": TT_ID + PAGIE_ID + 39,
    # "TT - Ann-Gree Acquired": TT_ID + PAGIE_ID + 40,
    # "TT - Fee-Dee Found": TT_ID + PAGIE_ID + 41,
    # "TT - Heidi Handled": TT_ID + PAGIE_ID + 42,
    # "TT - Evie Exorcised": TT_ID + PAGIE_ID + 43,
    "TT - Grand Tome Ghosts": TT_ID + PAGIE_ID + 44,
    "TT - Rampo's Rampagie": TT_ID + PAGIE_ID + 45,
    "TT - Pagie Piece 1": TT_ID + PAGIE_ID + 46,
    "TT - Pagie Piece 2": TT_ID + PAGIE_ID + 47,
    "TT - Pagie Piece 3": TT_ID + PAGIE_ID + 48,
    "TT - Pagie Piece 4": TT_ID + PAGIE_ID + 49,
    "TT - Pagie Piece 5": TT_ID + PAGIE_ID + 50,
    "TT - Pagie Piece 6": TT_ID + PAGIE_ID + 51,
    "TT - Pagie Piece 7": TT_ID + PAGIE_ID + 52,
    "TT - Pagie Piece 8": TT_ID + PAGIE_ID + 53,

    
        # Glitterglaze Glacier - Quills
    "GlGl - Quill 0": GL_ID + QUILL_ID + 0,
    "GlGl - Quill 1": GL_ID + QUILL_ID + 1,
    "GlGl - Quill 2": GL_ID + QUILL_ID + 2,
    "GlGl - Quill 3": GL_ID + QUILL_ID + 3,
    "GlGl - Quill 4": GL_ID + QUILL_ID + 4,
    "GlGl - Quill 5": GL_ID + QUILL_ID + 5,
    "GlGl - Quill 6": GL_ID + QUILL_ID + 6,
    "GlGl - Quill 7": GL_ID + QUILL_ID + 7,
    "GlGl - Quill 8": GL_ID + QUILL_ID + 8,
    "GlGl - Quill 9": GL_ID + QUILL_ID + 9,
    "GlGl - Quill 10": GL_ID + QUILL_ID + 10,
    "GlGl - Quill 11": GL_ID + QUILL_ID + 11,
    "GlGl - Quill 12": GL_ID + QUILL_ID + 12,
    "GlGl - Quill 13": GL_ID + QUILL_ID + 13,
    "GlGl - Quill 14": GL_ID + QUILL_ID + 14,
    "GlGl - Quill 15": GL_ID + QUILL_ID + 15,
    "GlGl - Quill 16": GL_ID + QUILL_ID + 16,
    "GlGl - Quill 17": GL_ID + QUILL_ID + 17,
    "GlGl - Quill 18": GL_ID + QUILL_ID + 18,
    "GlGl - Quill 19": GL_ID + QUILL_ID + 19,
    "GlGl - Quill 20": GL_ID + QUILL_ID + 20,
    "GlGl - Quill 21": GL_ID + QUILL_ID + 21,
    "GlGl - Quill 22": GL_ID + QUILL_ID + 22,
    "GlGl - Quill 23": GL_ID + QUILL_ID + 23,
    "GlGl - Quill 24": GL_ID + QUILL_ID + 24,
    "GlGl - Quill 25": GL_ID + QUILL_ID + 25,
    "GlGl - Quill 26": GL_ID + QUILL_ID + 26,
    "GlGl - Quill 27": GL_ID + QUILL_ID + 27,
    "GlGl - Quill 28": GL_ID + QUILL_ID + 28,
    "GlGl - Quill 29": GL_ID + QUILL_ID + 29,
    "GlGl - Quill 30": GL_ID + QUILL_ID + 30,
    "GlGl - Quill 31": GL_ID + QUILL_ID + 31,
    "GlGl - Quill 32": GL_ID + QUILL_ID + 32,
    "GlGl - Quill 33": GL_ID + QUILL_ID + 33,
    "GlGl - Quill 34": GL_ID + QUILL_ID + 34,
    "GlGl - Quill 35": GL_ID + QUILL_ID + 35,
    "GlGl - Quill 36": GL_ID + QUILL_ID + 36,
    "GlGl - Quill 37": GL_ID + QUILL_ID + 37,
    "GlGl - Quill 38": GL_ID + QUILL_ID + 38,
    "GlGl - Quill 39": GL_ID + QUILL_ID + 39,
    "GlGl - Quill 40": GL_ID + QUILL_ID + 40,
    "GlGl - Quill 41": GL_ID + QUILL_ID + 41,
    "GlGl - Quill 42": GL_ID + QUILL_ID + 42,
    "GlGl - Quill 43": GL_ID + QUILL_ID + 43,
    "GlGl - Quill 44": GL_ID + QUILL_ID + 44,
    "GlGl - Quill 45": GL_ID + QUILL_ID + 45,
    "GlGl - Quill 46": GL_ID + QUILL_ID + 46,
    "GlGl - Quill 47": GL_ID + QUILL_ID + 47,
    "GlGl - Quill 48": GL_ID + QUILL_ID + 48,
    "GlGl - Quill 49": GL_ID + QUILL_ID + 49,
    "GlGl - Quill 50": GL_ID + QUILL_ID + 50,
    "GlGl - Quill 51": GL_ID + QUILL_ID + 51,
    "GlGl - Quill 52": GL_ID + QUILL_ID + 52,
    "GlGl - Quill 53": GL_ID + QUILL_ID + 53,
    "GlGl - Quill 54": GL_ID + QUILL_ID + 54,
    "GlGl - Quill 55": GL_ID + QUILL_ID + 55,
    "GlGl - Quill 56": GL_ID + QUILL_ID + 56,
    "GlGl - Quill 57": GL_ID + QUILL_ID + 57,
    "GlGl - Quill 58": GL_ID + QUILL_ID + 58,
    "GlGl - Quill 59": GL_ID + QUILL_ID + 59,
    "GlGl - Quill 60": GL_ID + QUILL_ID + 60,
    "GlGl - Quill 61": GL_ID + QUILL_ID + 61,
    "GlGl - Quill 62": GL_ID + QUILL_ID + 62,
    "GlGl - Quill 63": GL_ID + QUILL_ID + 63,
    "GlGl - Quill 64": GL_ID + QUILL_ID + 64,
    "GlGl - Quill 65": GL_ID + QUILL_ID + 65,
    "GlGl - Quill 66": GL_ID + QUILL_ID + 66,
    "GlGl - Quill 67": GL_ID + QUILL_ID + 67,
    "GlGl - Quill 68": GL_ID + QUILL_ID + 68,
    "GlGl - Quill 69": GL_ID + QUILL_ID + 69,
    "GlGl - Quill 70": GL_ID + QUILL_ID + 70,
    "GlGl - Quill 71": GL_ID + QUILL_ID + 71,
    "GlGl - Quill 72": GL_ID + QUILL_ID + 72,
    "GlGl - Quill 73": GL_ID + QUILL_ID + 73,
    "GlGl - Quill 74": GL_ID + QUILL_ID + 74,
    "GlGl - Quill 75": GL_ID + QUILL_ID + 75,
    "GlGl - Quill 76": GL_ID + QUILL_ID + 76,
    "GlGl - Quill 77": GL_ID + QUILL_ID + 77,
    "GlGl - Quill 78": GL_ID + QUILL_ID + 78,
    "GlGl - Quill 79": GL_ID + QUILL_ID + 79,
    "GlGl - Quill 80": GL_ID + QUILL_ID + 80,
    "GlGl - Quill 81": GL_ID + QUILL_ID + 81,
    "GlGl - Quill 82": GL_ID + QUILL_ID + 82,
    "GlGl - Quill 83": GL_ID + QUILL_ID + 83,
    "GlGl - Quill 84": GL_ID + QUILL_ID + 84,
    "GlGl - Quill 85": GL_ID + QUILL_ID + 85,
    "GlGl - Quill 86": GL_ID + QUILL_ID + 86,
    "GlGl - Quill 87": GL_ID + QUILL_ID + 87,
    "GlGl - Quill 88": GL_ID + QUILL_ID + 88,
    "GlGl - Quill 89": GL_ID + QUILL_ID + 89,
    "GlGl - Quill 90": GL_ID + QUILL_ID + 90,
    "GlGl - Quill 91": GL_ID + QUILL_ID + 91,
    "GlGl - Quill 92": GL_ID + QUILL_ID + 92,
    "GlGl - Quill 93": GL_ID + QUILL_ID + 93,
    "GlGl - Quill 94": GL_ID + QUILL_ID + 94,
    "GlGl - Quill 95": GL_ID + QUILL_ID + 95,
    "GlGl - Quill 96": GL_ID + QUILL_ID + 96,
    "GlGl - Quill 97": GL_ID + QUILL_ID + 97,
    "GlGl - Quill 98": GL_ID + QUILL_ID + 98,
    "GlGl - Quill 99": GL_ID + QUILL_ID + 99,
    "GlGl - Quill 100": GL_ID + QUILL_ID + 100,
    "GlGl - Quill 101": GL_ID + QUILL_ID + 101,
    "GlGl - Quill 102": GL_ID + QUILL_ID + 102,
    "GlGl - Quill 103": GL_ID + QUILL_ID + 103,
    "GlGl - Quill 104": GL_ID + QUILL_ID + 104,
    "GlGl - Quill 105": GL_ID + QUILL_ID + 105,
    "GlGl - Quill 106": GL_ID + QUILL_ID + 106,
    "GlGl - Quill 107": GL_ID + QUILL_ID + 107,
    "GlGl - Quill 108": GL_ID + QUILL_ID + 108,
    "GlGl - Quill 109": GL_ID + QUILL_ID + 109,
    "GlGl - Quill 110": GL_ID + QUILL_ID + 110,
    "GlGl - Quill 111": GL_ID + QUILL_ID + 111,
    "GlGl - Quill 112": GL_ID + QUILL_ID + 112,
    "GlGl - Quill 113": GL_ID + QUILL_ID + 113,
    "GlGl - Quill 114": GL_ID + QUILL_ID + 114,
    "GlGl - Quill 115": GL_ID + QUILL_ID + 115,
    "GlGl - Quill 116": GL_ID + QUILL_ID + 116,
    "GlGl - Quill 117": GL_ID + QUILL_ID + 117,
    "GlGl - Quill 118": GL_ID + QUILL_ID + 118,
    "GlGl - Quill 119": GL_ID + QUILL_ID + 119,
    "GlGl - Quill 120": GL_ID + QUILL_ID + 120,
    "GlGl - Quill 121": GL_ID + QUILL_ID + 121,
    "GlGl - Quill 122": GL_ID + QUILL_ID + 122,
    "GlGl - Quill 123": GL_ID + QUILL_ID + 123,
    "GlGl - Quill 124": GL_ID + QUILL_ID + 124,
    "GlGl - Quill 125": GL_ID + QUILL_ID + 125,
    "GlGl - Quill 126": GL_ID + QUILL_ID + 126,
    "GlGl - Quill 127": GL_ID + QUILL_ID + 127,
    "GlGl - Quill 128": GL_ID + QUILL_ID + 128,
    "GlGl - Quill 129": GL_ID + QUILL_ID + 129,
    "GlGl - Quill 130": GL_ID + QUILL_ID + 130,
    "GlGl - Quill 131": GL_ID + QUILL_ID + 131,
    "GlGl - Quill 132": GL_ID + QUILL_ID + 132,
    "GlGl - Quill 133": GL_ID + QUILL_ID + 133,
    "GlGl - Quill 134": GL_ID + QUILL_ID + 134,
    "GlGl - Quill 135": GL_ID + QUILL_ID + 135,
    "GlGl - Quill 136": GL_ID + QUILL_ID + 136,
    "GlGl - Quill 137": GL_ID + QUILL_ID + 137,
    "GlGl - Quill 138": GL_ID + QUILL_ID + 138,
    "GlGl - Quill 139": GL_ID + QUILL_ID + 139,
    "GlGl - Quill 140": GL_ID + QUILL_ID + 140,
    "GlGl - Quill 141": GL_ID + QUILL_ID + 141,
    "GlGl - Quill 142": GL_ID + QUILL_ID + 142,
    "GlGl - Quill 143": GL_ID + QUILL_ID + 143,
    "GlGl - Quill 144": GL_ID + QUILL_ID + 144,
    "GlGl - Quill 145": GL_ID + QUILL_ID + 145,
    "GlGl - Quill 146": GL_ID + QUILL_ID + 146,
    "GlGl - Quill 147": GL_ID + QUILL_ID + 147,
    "GlGl - Quill 148": GL_ID + QUILL_ID + 148,
    "GlGl - Quill 149": GL_ID + QUILL_ID + 149,
    
       # Gliterglaze Glacier - Pagies
    "GlGl - Crystal Clear": GL_ID + PAGIE_ID + 0,
    "GlGl - Burning Beacons": GL_ID + PAGIE_ID + 1,
    # "GlGl - Normy Nabbed": GL_ID + PAGIE_ID + 2,
    # "GlGl - Ann-Gree Acquired": GL_ID + PAGIE_ID + 3,
    # "GlGl - Fee-Dee Found": GL_ID + PAGIE_ID + 4,
    # "GlGl - Heidi Handled": GL_ID + PAGIE_ID + 5,
    # "GlGl - Evie Exorcised": GL_ID + PAGIE_ID + 6,
    "GlGl - Glacial Glide": GL_ID + PAGIE_ID + 7,
    "GlGl - Collect all the Quills": GL_ID + PAGIE_ID + 8,
    # "GlGl - 4 Pagie Pieces": GL_ID + PAGIE_ID + 9,
    # "GlGl - 4 More Pagie Pieces": GL_ID + PAGIE_ID + 10,
    "GlGl - Kartos (Bronze)": GL_ID + PAGIE_ID + 11,
    "GlGl - Kartos (Silver)": GL_ID + PAGIE_ID + 12,
    "GlGl - Kartos (Gold)": GL_ID + PAGIE_ID + 13,
    "GlGl - Rextro (Bronze)": GL_ID + PAGIE_ID + 14,
    "GlGl - Rextro (Silver)": GL_ID + PAGIE_ID + 15,
    "GlGl - Rextro (Gold)": GL_ID + PAGIE_ID + 16,
    "GlGl - Fancy Finery": GL_ID + PAGIE_ID + 17,
    "GlGl - Blowie Bother": GL_ID + PAGIE_ID + 18,
    "GlGl - Iceberg Bounty": GL_ID + PAGIE_ID + 19,
    "GlGl - Fizzics Puzzle": GL_ID + PAGIE_ID + 20,
    "GlGl - Jellyfishtery": GL_ID + PAGIE_ID + 21,
    "GlGl - Moving Mayhem": GL_ID + PAGIE_ID + 22,
    "GlGl - Grotto Winner": GL_ID + PAGIE_ID + 23,
    "GlGl - Haggard Headwear": GL_ID + PAGIE_ID + 24,
    "GlGl - Bombs Away": GL_ID + PAGIE_ID + 25,
    "GlGl - Awesome Arrr-tefact": GL_ID + PAGIE_ID + 26,
    "GlGl - Cliffside Chest": GL_ID + PAGIE_ID + 27,
    "GlGl - Herding Hat": GL_ID + PAGIE_ID + 28,
    "GlGl - Village Snowdown": GL_ID + PAGIE_ID + 29,
    "GlGl - Pants, Very Much": GL_ID + PAGIE_ID + 30,
    "GlGl - Freezing Flight": GL_ID + PAGIE_ID + 31,
    "GlGl - Coin Clearer": GL_ID + PAGIE_ID + 32,
    "GlGl - Capital Block": GL_ID + PAGIE_ID + 33,
    "GlGl - Artic Artist": GL_ID + PAGIE_ID + 34,
    "GlGl - Chilly Target": GL_ID + PAGIE_ID + 35,
    "GlGl - Incredible Quiz": GL_ID + PAGIE_ID + 36,
    "GlGl - Ice-Scape": GL_ID + PAGIE_ID + 37,
    "GlGl - Worrying Walls": GL_ID + PAGIE_ID + 38,
    "GlGl - Toxic Trouble": GL_ID + PAGIE_ID + 39,
    "GlGl - Keepy Uppy": GL_ID + PAGIE_ID + 40,
    "GlGl - Chilly Combat": GL_ID + PAGIE_ID + 41,
    "GlGl - Snowball Scramble": GL_ID + PAGIE_ID + 42,
    "GlGl - Precarious Pipes": GL_ID + PAGIE_ID + 43,
    "GlGl - Brrreeze Blocked": GL_ID + PAGIE_ID + 44,
    "GlGl - Grand Tome Ghosts": GL_ID + PAGIE_ID + 45,
    "GlGl - Pagie Piece 1": GL_ID + PAGIE_ID + 46,
    "GlGl - Pagie Piece 2": GL_ID + PAGIE_ID + 47,
    "GlGl - Pagie Piece 3": GL_ID + PAGIE_ID + 48,
    "GlGl - Pagie Piece 4": GL_ID + PAGIE_ID + 49,
    "GlGl - Pagie Piece 5": GL_ID + PAGIE_ID + 50,
    "GlGl - Pagie Piece 6": GL_ID + PAGIE_ID + 51,
    "GlGl - Pagie Piece 7": GL_ID + PAGIE_ID + 52,
    "GlGl - Pagie Piece 8": GL_ID + PAGIE_ID + 53,

    
         # Moodymaze Marsh - Quills
    "MM - Quill 0": MM_ID + QUILL_ID + 0,
    "MM - Quill 1": MM_ID + QUILL_ID + 1,
    "MM - Quill 2": MM_ID + QUILL_ID + 2,
    "MM - Quill 3": MM_ID + QUILL_ID + 3,
    "MM - Quill 4": MM_ID + QUILL_ID + 4,
    "MM - Quill 5": MM_ID + QUILL_ID + 5,
    "MM - Quill 6": MM_ID + QUILL_ID + 6,
    "MM - Quill 7": MM_ID + QUILL_ID + 7,
    "MM - Quill 8": MM_ID + QUILL_ID + 8,
    "MM - Quill 9": MM_ID + QUILL_ID + 9,
    "MM - Quill 10": MM_ID + QUILL_ID + 10,
    "MM - Quill 11": MM_ID + QUILL_ID + 11,
    "MM - Quill 12": MM_ID + QUILL_ID + 12,
    "MM - Quill 13": MM_ID + QUILL_ID + 13,
    "MM - Quill 14": MM_ID + QUILL_ID + 14,
    "MM - Quill 15": MM_ID + QUILL_ID + 15,
    "MM - Quill 16": MM_ID + QUILL_ID + 16,
    "MM - Quill 17": MM_ID + QUILL_ID + 17,
    "MM - Quill 18": MM_ID + QUILL_ID + 18,
    "MM - Quill 19": MM_ID + QUILL_ID + 19,
    "MM - Quill 20": MM_ID + QUILL_ID + 20,
    "MM - Quill 21": MM_ID + QUILL_ID + 21,
    "MM - Quill 22": MM_ID + QUILL_ID + 22,
    "MM - Quill 23": MM_ID + QUILL_ID + 23,
    "MM - Quill 24": MM_ID + QUILL_ID + 24,
    "MM - Quill 25": MM_ID + QUILL_ID + 25,
    "MM - Quill 26": MM_ID + QUILL_ID + 26,
    "MM - Quill 27": MM_ID + QUILL_ID + 27,
    "MM - Quill 28": MM_ID + QUILL_ID + 28,
    "MM - Quill 29": MM_ID + QUILL_ID + 29,
    "MM - Quill 30": MM_ID + QUILL_ID + 30,
    "MM - Quill 31": MM_ID + QUILL_ID + 31,
    "MM - Quill 32": MM_ID + QUILL_ID + 32,
    "MM - Quill 33": MM_ID + QUILL_ID + 33,
    "MM - Quill 34": MM_ID + QUILL_ID + 34,
    "MM - Quill 35": MM_ID + QUILL_ID + 35,
    "MM - Quill 36": MM_ID + QUILL_ID + 36,
    "MM - Quill 37": MM_ID + QUILL_ID + 37,
    "MM - Quill 38": MM_ID + QUILL_ID + 38,
    "MM - Quill 39": MM_ID + QUILL_ID + 39,
    "MM - Quill 40": MM_ID + QUILL_ID + 40,
    "MM - Quill 41": MM_ID + QUILL_ID + 41,
    "MM - Quill 42": MM_ID + QUILL_ID + 42,
    "MM - Quill 43": MM_ID + QUILL_ID + 43,
    "MM - Quill 44": MM_ID + QUILL_ID + 44,
    "MM - Quill 45": MM_ID + QUILL_ID + 45,
    "MM - Quill 46": MM_ID + QUILL_ID + 46,
    "MM - Quill 47": MM_ID + QUILL_ID + 47,
    "MM - Quill 48": MM_ID + QUILL_ID + 48,
    "MM - Quill 49": MM_ID + QUILL_ID + 49,
    "MM - Quill 50": MM_ID + QUILL_ID + 50,
    "MM - Quill 51": MM_ID + QUILL_ID + 51,
    "MM - Quill 52": MM_ID + QUILL_ID + 52,
    "MM - Quill 53": MM_ID + QUILL_ID + 53,
    "MM - Quill 54": MM_ID + QUILL_ID + 54,
    "MM - Quill 55": MM_ID + QUILL_ID + 55,
    "MM - Quill 56": MM_ID + QUILL_ID + 56,
    "MM - Quill 57": MM_ID + QUILL_ID + 57,
    "MM - Quill 58": MM_ID + QUILL_ID + 58,
    "MM - Quill 59": MM_ID + QUILL_ID + 59,
    "MM - Quill 60": MM_ID + QUILL_ID + 60,
    "MM - Quill 61": MM_ID + QUILL_ID + 61,
    "MM - Quill 62": MM_ID + QUILL_ID + 62,
    "MM - Quill 63": MM_ID + QUILL_ID + 63,
    "MM - Quill 64": MM_ID + QUILL_ID + 64,
    "MM - Quill 65": MM_ID + QUILL_ID + 65,
    "MM - Quill 66": MM_ID + QUILL_ID + 66,
    "MM - Quill 67": MM_ID + QUILL_ID + 67,
    "MM - Quill 68": MM_ID + QUILL_ID + 68,
    "MM - Quill 69": MM_ID + QUILL_ID + 69,
    "MM - Quill 70": MM_ID + QUILL_ID + 70,
    "MM - Quill 71": MM_ID + QUILL_ID + 71,
    "MM - Quill 72": MM_ID + QUILL_ID + 72,
    "MM - Quill 73": MM_ID + QUILL_ID + 73,
    "MM - Quill 74": MM_ID + QUILL_ID + 74,
    "MM - Quill 75": MM_ID + QUILL_ID + 75,
    "MM - Quill 76": MM_ID + QUILL_ID + 76,
    "MM - Quill 77": MM_ID + QUILL_ID + 77,
    "MM - Quill 78": MM_ID + QUILL_ID + 78,
    "MM - Quill 79": MM_ID + QUILL_ID + 79,
    "MM - Quill 80": MM_ID + QUILL_ID + 80,
    "MM - Quill 81": MM_ID + QUILL_ID + 81,
    "MM - Quill 82": MM_ID + QUILL_ID + 82,
    "MM - Quill 83": MM_ID + QUILL_ID + 83,
    "MM - Quill 84": MM_ID + QUILL_ID + 84,
    "MM - Quill 85": MM_ID + QUILL_ID + 85,
    "MM - Quill 86": MM_ID + QUILL_ID + 86,
    "MM - Quill 87": MM_ID + QUILL_ID + 87,
    "MM - Quill 88": MM_ID + QUILL_ID + 88,
    "MM - Quill 89": MM_ID + QUILL_ID + 89,
    "MM - Quill 90": MM_ID + QUILL_ID + 90,
    "MM - Quill 91": MM_ID + QUILL_ID + 91,
    "MM - Quill 92": MM_ID + QUILL_ID + 92,
    "MM - Quill 93": MM_ID + QUILL_ID + 93,
    "MM - Quill 94": MM_ID + QUILL_ID + 94,
    "MM - Quill 95": MM_ID + QUILL_ID + 95,
    "MM - Quill 96": MM_ID + QUILL_ID + 96,
    "MM - Quill 97": MM_ID + QUILL_ID + 97,
    "MM - Quill 98": MM_ID + QUILL_ID + 98,
    "MM - Quill 99": MM_ID + QUILL_ID + 99,
    "MM - Quill 100": MM_ID + QUILL_ID + 100,
    "MM - Quill 101": MM_ID + QUILL_ID + 101,
    "MM - Quill 102": MM_ID + QUILL_ID + 102,
    "MM - Quill 103": MM_ID + QUILL_ID + 103,
    "MM - Quill 104": MM_ID + QUILL_ID + 104,
    "MM - Quill 105": MM_ID + QUILL_ID + 105,
    "MM - Quill 106": MM_ID + QUILL_ID + 106,
    "MM - Quill 107": MM_ID + QUILL_ID + 107,
    "MM - Quill 108": MM_ID + QUILL_ID + 108,
    "MM - Quill 109": MM_ID + QUILL_ID + 109,
    "MM - Quill 110": MM_ID + QUILL_ID + 110,
    "MM - Quill 111": MM_ID + QUILL_ID + 111,
    "MM - Quill 112": MM_ID + QUILL_ID + 112,
    "MM - Quill 113": MM_ID + QUILL_ID + 113,
    "MM - Quill 114": MM_ID + QUILL_ID + 114,
    "MM - Quill 115": MM_ID + QUILL_ID + 115,
    "MM - Quill 116": MM_ID + QUILL_ID + 116,
    "MM - Quill 117": MM_ID + QUILL_ID + 117,
    "MM - Quill 118": MM_ID + QUILL_ID + 118,
    "MM - Quill 119": MM_ID + QUILL_ID + 119,
    "MM - Quill 120": MM_ID + QUILL_ID + 120,
    "MM - Quill 121": MM_ID + QUILL_ID + 121,
    "MM - Quill 122": MM_ID + QUILL_ID + 122,
    "MM - Quill 123": MM_ID + QUILL_ID + 123,
    "MM - Quill 124": MM_ID + QUILL_ID + 124,
    "MM - Quill 125": MM_ID + QUILL_ID + 125,
    "MM - Quill 126": MM_ID + QUILL_ID + 126,
    "MM - Quill 127": MM_ID + QUILL_ID + 127,
    "MM - Quill 128": MM_ID + QUILL_ID + 128,
    "MM - Quill 129": MM_ID + QUILL_ID + 129,
    "MM - Quill 130": MM_ID + QUILL_ID + 130,
    "MM - Quill 131": MM_ID + QUILL_ID + 131,
    "MM - Quill 132": MM_ID + QUILL_ID + 132,
    "MM - Quill 133": MM_ID + QUILL_ID + 133,
    "MM - Quill 134": MM_ID + QUILL_ID + 134,
    "MM - Quill 135": MM_ID + QUILL_ID + 135,
    "MM - Quill 136": MM_ID + QUILL_ID + 136,
    "MM - Quill 137": MM_ID + QUILL_ID + 137,
    "MM - Quill 138": MM_ID + QUILL_ID + 138,
    "MM - Quill 139": MM_ID + QUILL_ID + 139,
    "MM - Quill 140": MM_ID + QUILL_ID + 140,
    "MM - Quill 141": MM_ID + QUILL_ID + 141,
    "MM - Quill 142": MM_ID + QUILL_ID + 142,
    "MM - Quill 143": MM_ID + QUILL_ID + 143,
    "MM - Quill 144": MM_ID + QUILL_ID + 144,
    "MM - Quill 145": MM_ID + QUILL_ID + 145,
    "MM - Quill 146": MM_ID + QUILL_ID + 146,
    "MM - Quill 147": MM_ID + QUILL_ID + 147,
    "MM - Quill 148": MM_ID + QUILL_ID + 148,
    "MM - Quill 149": MM_ID + QUILL_ID + 149,
    
           # Moodymaze Marsh - Pagies
    "MM - Curled Up Course": MM_ID + PAGIE_ID + 0,
    "MM - Off-Road Reward": MM_ID + PAGIE_ID + 1,
    "MM - Collect all the Quills": MM_ID + PAGIE_ID + 2,
    # "MM - 4 Pagie Pieces": MM_ID + PAGIE_ID + 3,
    # "MM - 4 More Pagie Pieces": MM_ID + PAGIE_ID + 4,
    "MM - Floating Folly": MM_ID + PAGIE_ID + 5,
    "MM - Rextro (Bronze)": MM_ID + PAGIE_ID + 6,
    "MM - Rextro (Silver)": MM_ID + PAGIE_ID + 7,
    "MM - Rextro (Gold)": MM_ID + PAGIE_ID + 8,
    "MM - Kartos (Bronze)": MM_ID + PAGIE_ID + 9,
    "MM - Kartos (Silver)": MM_ID + PAGIE_ID + 10,
    "MM - Kartos (Gold)": MM_ID + PAGIE_ID + 11,
    "MM - Maze Up!": MM_ID + PAGIE_ID + 12,
    "MM - Ollie's Moving Maze": MM_ID + PAGIE_ID + 13,
    "MM - Letting Off Steam": MM_ID + PAGIE_ID + 14,
    "MM - Toadstool Destruction": MM_ID + PAGIE_ID + 15,
    # "MM - Ann-Gree Acquired": MM_ID + PAGIE_ID + 16,
    # "MM - Evie Exorcised": MM_ID + PAGIE_ID + 17,
    # "MM - Fee-Dee Found": MM_ID + PAGIE_ID + 18,
    # "MM - Heidi Handled": MM_ID + PAGIE_ID + 19,
    # "MM - Normy Nabbed": MM_ID + PAGIE_ID + 20,
    "MM - Marsh Match": MM_ID + PAGIE_ID + 21,
    "MM - Lash Chance": MM_ID + PAGIE_ID + 22,
    "MM - Incredibubble!": MM_ID + PAGIE_ID + 23,
    "MM - Current Commotion": MM_ID + PAGIE_ID + 24,
    # "MM - An A-maze-ing Time": MM_ID + PAGIE_ID + 25,
    "MM - Toasty Traversal": MM_ID + PAGIE_ID + 26,
    "MM - Pressure Timer": MM_ID + PAGIE_ID + 27,
    "MM - Jack's Jaunt": MM_ID + PAGIE_ID + 28,
    "MM - Jack Again": MM_ID + PAGIE_ID + 29,
    "MM - Fog-otten Treasure": MM_ID + PAGIE_ID + 30,
    "MM - Fungi Fun": MM_ID + PAGIE_ID + 31,
    "MM - Rope Burn": MM_ID + PAGIE_ID + 32,
    "MM - Cephalopod Circuit": MM_ID + PAGIE_ID + 33,
    "MM - Hardheaded": MM_ID + PAGIE_ID + 34,
    "MM - Fairy Ring Fun": MM_ID + PAGIE_ID + 35,
    "MM - Suspicious Stone": MM_ID + PAGIE_ID + 36,
    "MM - Pipe Down": MM_ID + PAGIE_ID + 37,
    "MM - Lantern Lark": MM_ID + PAGIE_ID + 38,
    "MM - Thorn Free": MM_ID + PAGIE_ID + 39,
    "MM - Sunken Sewer": MM_ID + PAGIE_ID + 40,
    "MM - Shoal Business": MM_ID + PAGIE_ID + 41,
    "MM - Emergency Stash": MM_ID + PAGIE_ID + 42,
    "MM - Swamp Station Situation": MM_ID + PAGIE_ID + 43,
    "MM - Grand Tome Ghosts": MM_ID + PAGIE_ID + 44,
    "MM - Tentacle Test": MM_ID + PAGIE_ID + 45,
    "MM - Pagie Piece 1": MM_ID + PAGIE_ID + 46,
    "MM - Pagie Piece 2": MM_ID + PAGIE_ID + 47,
    "MM - Pagie Piece 3": MM_ID + PAGIE_ID + 48,
    "MM - Pagie Piece 4": MM_ID + PAGIE_ID + 49,
    "MM - Pagie Piece 5": MM_ID + PAGIE_ID + 50,
    "MM - Pagie Piece 6": MM_ID + PAGIE_ID + 51,
    "MM - Pagie Piece 7": MM_ID + PAGIE_ID + 52,
    "MM - Pagie Piece 8": MM_ID + PAGIE_ID + 53,

    
             # Capital Cashino - Quills
    "CC - Quill 0": CC_ID + QUILL_ID + 0,
    "CC - Quill 1": CC_ID + QUILL_ID + 1,
    "CC - Quill 2": CC_ID + QUILL_ID + 2,
    "CC - Quill 3": CC_ID + QUILL_ID + 3,
    "CC - Quill 4": CC_ID + QUILL_ID + 4,
    "CC - Quill 5": CC_ID + QUILL_ID + 5,
    "CC - Quill 6": CC_ID + QUILL_ID + 6,
    "CC - Quill 7": CC_ID + QUILL_ID + 7,
    "CC - Quill 8": CC_ID + QUILL_ID + 8,
    "CC - Quill 9": CC_ID + QUILL_ID + 9,
    "CC - Quill 10": CC_ID + QUILL_ID + 10,
    "CC - Quill 11": CC_ID + QUILL_ID + 11,
    "CC - Quill 12": CC_ID + QUILL_ID + 12,
    "CC - Quill 13": CC_ID + QUILL_ID + 13,
    "CC - Quill 14": CC_ID + QUILL_ID + 14,
    "CC - Quill 15": CC_ID + QUILL_ID + 15,
    "CC - Quill 16": CC_ID + QUILL_ID + 16,
    "CC - Quill 17": CC_ID + QUILL_ID + 17,
    "CC - Quill 18": CC_ID + QUILL_ID + 18,
    "CC - Quill 19": CC_ID + QUILL_ID + 19,
    "CC - Quill 20": CC_ID + QUILL_ID + 20,
    "CC - Quill 21": CC_ID + QUILL_ID + 21,
    "CC - Quill 22": CC_ID + QUILL_ID + 22,
    "CC - Quill 23": CC_ID + QUILL_ID + 23,
    "CC - Quill 24": CC_ID + QUILL_ID + 24,
    "CC - Quill 25": CC_ID + QUILL_ID + 25,
    "CC - Quill 26": CC_ID + QUILL_ID + 26,
    "CC - Quill 27": CC_ID + QUILL_ID + 27,
    "CC - Quill 28": CC_ID + QUILL_ID + 28,
    "CC - Quill 29": CC_ID + QUILL_ID + 29,
    "CC - Quill 30": CC_ID + QUILL_ID + 30,
    "CC - Quill 31": CC_ID + QUILL_ID + 31,
    "CC - Quill 32": CC_ID + QUILL_ID + 32,
    "CC - Quill 33": CC_ID + QUILL_ID + 33,
    "CC - Quill 34": CC_ID + QUILL_ID + 34,
    "CC - Quill 35": CC_ID + QUILL_ID + 35,
    "CC - Quill 36": CC_ID + QUILL_ID + 36,
    "CC - Quill 37": CC_ID + QUILL_ID + 37,
    "CC - Quill 38": CC_ID + QUILL_ID + 38,
    "CC - Quill 39": CC_ID + QUILL_ID + 39,
    "CC - Quill 40": CC_ID + QUILL_ID + 40,
    "CC - Quill 41": CC_ID + QUILL_ID + 41,
    "CC - Quill 42": CC_ID + QUILL_ID + 42,
    "CC - Quill 43": CC_ID + QUILL_ID + 43,
    "CC - Quill 44": CC_ID + QUILL_ID + 44,
    "CC - Quill 45": CC_ID + QUILL_ID + 45,
    "CC - Quill 46": CC_ID + QUILL_ID + 46,
    "CC - Quill 47": CC_ID + QUILL_ID + 47,
    "CC - Quill 48": CC_ID + QUILL_ID + 48,
    "CC - Quill 49": CC_ID + QUILL_ID + 49,
    "CC - Quill 50": CC_ID + QUILL_ID + 50,
    "CC - Quill 51": CC_ID + QUILL_ID + 51,
    "CC - Quill 52": CC_ID + QUILL_ID + 52,
    "CC - Quill 53": CC_ID + QUILL_ID + 53,
    "CC - Quill 54": CC_ID + QUILL_ID + 54,
    "CC - Quill 55": CC_ID + QUILL_ID + 55,
    "CC - Quill 56": CC_ID + QUILL_ID + 56,
    "CC - Quill 57": CC_ID + QUILL_ID + 57,
    "CC - Quill 58": CC_ID + QUILL_ID + 58,
    "CC - Quill 59": CC_ID + QUILL_ID + 59,
    "CC - Quill 60": CC_ID + QUILL_ID + 60,
    "CC - Quill 61": CC_ID + QUILL_ID + 61,
    "CC - Quill 62": CC_ID + QUILL_ID + 62,
    "CC - Quill 63": CC_ID + QUILL_ID + 63,
    "CC - Quill 64": CC_ID + QUILL_ID + 64,
    "CC - Quill 65": CC_ID + QUILL_ID + 65,
    "CC - Quill 66": CC_ID + QUILL_ID + 66,
    "CC - Quill 67": CC_ID + QUILL_ID + 67,
    "CC - Quill 68": CC_ID + QUILL_ID + 68,
    "CC - Quill 69": CC_ID + QUILL_ID + 69,
    "CC - Quill 70": CC_ID + QUILL_ID + 70,
    "CC - Quill 71": CC_ID + QUILL_ID + 71,
    "CC - Quill 72": CC_ID + QUILL_ID + 72,
    "CC - Quill 73": CC_ID + QUILL_ID + 73,
    "CC - Quill 74": CC_ID + QUILL_ID + 74,
    "CC - Quill 75": CC_ID + QUILL_ID + 75,
    "CC - Quill 76": CC_ID + QUILL_ID + 76,
    "CC - Quill 77": CC_ID + QUILL_ID + 77,
    "CC - Quill 78": CC_ID + QUILL_ID + 78,
    "CC - Quill 79": CC_ID + QUILL_ID + 79,
    "CC - Quill 80": CC_ID + QUILL_ID + 80,
    "CC - Quill 81": CC_ID + QUILL_ID + 81,
    "CC - Quill 82": CC_ID + QUILL_ID + 82,
    "CC - Quill 83": CC_ID + QUILL_ID + 83,
    "CC - Quill 84": CC_ID + QUILL_ID + 84,
    "CC - Quill 85": CC_ID + QUILL_ID + 85,
    "CC - Quill 86": CC_ID + QUILL_ID + 86,
    "CC - Quill 87": CC_ID + QUILL_ID + 87,
    "CC - Quill 88": CC_ID + QUILL_ID + 88,
    "CC - Quill 89": CC_ID + QUILL_ID + 89,
    "CC - Quill 90": CC_ID + QUILL_ID + 90,
    "CC - Quill 91": CC_ID + QUILL_ID + 91,
    "CC - Quill 92": CC_ID + QUILL_ID + 92,
    "CC - Quill 93": CC_ID + QUILL_ID + 93,
    "CC - Quill 94": CC_ID + QUILL_ID + 94,
    "CC - Quill 95": CC_ID + QUILL_ID + 95,
    "CC - Quill 96": CC_ID + QUILL_ID + 96,
    "CC - Quill 97": CC_ID + QUILL_ID + 97,
    "CC - Quill 98": CC_ID + QUILL_ID + 98,
    "CC - Quill 99": CC_ID + QUILL_ID + 99,
    "CC - Quill 100": CC_ID + QUILL_ID + 100,
    "CC - Quill 101": CC_ID + QUILL_ID + 101,
    "CC - Quill 102": CC_ID + QUILL_ID + 102,
    "CC - Quill 103": CC_ID + QUILL_ID + 103,
    "CC - Quill 104": CC_ID + QUILL_ID + 104,
    "CC - Quill 105": CC_ID + QUILL_ID + 105,
    "CC - Quill 106": CC_ID + QUILL_ID + 106,
    "CC - Quill 107": CC_ID + QUILL_ID + 107,
    "CC - Quill 108": CC_ID + QUILL_ID + 108,
    "CC - Quill 109": CC_ID + QUILL_ID + 109,
    "CC - Quill 110": CC_ID + QUILL_ID + 110,
    "CC - Quill 111": CC_ID + QUILL_ID + 111,
    "CC - Quill 112": CC_ID + QUILL_ID + 112,
    "CC - Quill 113": CC_ID + QUILL_ID + 113,
    "CC - Quill 114": CC_ID + QUILL_ID + 114,
    "CC - Quill 115": CC_ID + QUILL_ID + 115,
    "CC - Quill 116": CC_ID + QUILL_ID + 116,
    "CC - Quill 117": CC_ID + QUILL_ID + 117,
    "CC - Quill 118": CC_ID + QUILL_ID + 118,
    "CC - Quill 119": CC_ID + QUILL_ID + 119,
    "CC - Quill 120": CC_ID + QUILL_ID + 120,
    "CC - Quill 121": CC_ID + QUILL_ID + 121,
    "CC - Quill 122": CC_ID + QUILL_ID + 122,
    "CC - Quill 123": CC_ID + QUILL_ID + 123,
    "CC - Quill 124": CC_ID + QUILL_ID + 124,
    "CC - Quill 125": CC_ID + QUILL_ID + 125,
    "CC - Quill 126": CC_ID + QUILL_ID + 126,
    "CC - Quill 127": CC_ID + QUILL_ID + 127,
    "CC - Quill 128": CC_ID + QUILL_ID + 128,
    "CC - Quill 129": CC_ID + QUILL_ID + 129,
    "CC - Quill 130": CC_ID + QUILL_ID + 130,
    "CC - Quill 131": CC_ID + QUILL_ID + 131,
    "CC - Quill 132": CC_ID + QUILL_ID + 132,
    "CC - Quill 133": CC_ID + QUILL_ID + 133,
    "CC - Quill 134": CC_ID + QUILL_ID + 134,
    "CC - Quill 135": CC_ID + QUILL_ID + 135,
    "CC - Quill 136": CC_ID + QUILL_ID + 136,
    "CC - Quill 137": CC_ID + QUILL_ID + 137,
    "CC - Quill 138": CC_ID + QUILL_ID + 138,
    "CC - Quill 139": CC_ID + QUILL_ID + 139,
    "CC - Quill 140": CC_ID + QUILL_ID + 140,
    "CC - Quill 141": CC_ID + QUILL_ID + 141,
    "CC - Quill 142": CC_ID + QUILL_ID + 142,
    "CC - Quill 143": CC_ID + QUILL_ID + 143,
    "CC - Quill 144": CC_ID + QUILL_ID + 144,
    "CC - Quill 145": CC_ID + QUILL_ID + 145,
    "CC - Quill 146": CC_ID + QUILL_ID + 146,
    "CC - Quill 147": CC_ID + QUILL_ID + 147,
    "CC - Quill 148": CC_ID + QUILL_ID + 148,
    "CC - Quill 149": CC_ID + QUILL_ID + 149,
    
     # Capital Cashino - Casino Tokens. Replaylee already exposes these with stable indices 1-150.
    "CC - Casino Token 1": CC_ID + CASINO_TOKEN_ID + 1,
    "CC - Casino Token 2": CC_ID + CASINO_TOKEN_ID + 2,
    "CC - Casino Token 3": CC_ID + CASINO_TOKEN_ID + 3,
    "CC - Casino Token 4": CC_ID + CASINO_TOKEN_ID + 4,
    "CC - Casino Token 5": CC_ID + CASINO_TOKEN_ID + 5,
    "CC - Casino Token 6": CC_ID + CASINO_TOKEN_ID + 6,
    "CC - Casino Token 7": CC_ID + CASINO_TOKEN_ID + 7,
    "CC - Casino Token 8": CC_ID + CASINO_TOKEN_ID + 8,
    "CC - Casino Token 9": CC_ID + CASINO_TOKEN_ID + 9,
    "CC - Casino Token 10": CC_ID + CASINO_TOKEN_ID + 10,
    "CC - Casino Token 11": CC_ID + CASINO_TOKEN_ID + 11,
    "CC - Casino Token 12": CC_ID + CASINO_TOKEN_ID + 12,
    "CC - Casino Token 13": CC_ID + CASINO_TOKEN_ID + 13,
    "CC - Casino Token 14": CC_ID + CASINO_TOKEN_ID + 14,
    "CC - Casino Token 15": CC_ID + CASINO_TOKEN_ID + 15,
    "CC - Casino Token 16": CC_ID + CASINO_TOKEN_ID + 16,
    "CC - Casino Token 17": CC_ID + CASINO_TOKEN_ID + 17,
    "CC - Casino Token 18": CC_ID + CASINO_TOKEN_ID + 18,
    "CC - Casino Token 19": CC_ID + CASINO_TOKEN_ID + 19,
    "CC - Casino Token 20": CC_ID + CASINO_TOKEN_ID + 20,
    "CC - Casino Token 21": CC_ID + CASINO_TOKEN_ID + 21,
    "CC - Casino Token 22": CC_ID + CASINO_TOKEN_ID + 22,
    "CC - Casino Token 23": CC_ID + CASINO_TOKEN_ID + 23,
    "CC - Casino Token 24": CC_ID + CASINO_TOKEN_ID + 24,
    "CC - Casino Token 25": CC_ID + CASINO_TOKEN_ID + 25,
    "CC - Casino Token 26": CC_ID + CASINO_TOKEN_ID + 26,
    "CC - Casino Token 27": CC_ID + CASINO_TOKEN_ID + 27,
    "CC - Casino Token 28": CC_ID + CASINO_TOKEN_ID + 28,
    "CC - Casino Token 29": CC_ID + CASINO_TOKEN_ID + 29,
    "CC - Casino Token 30": CC_ID + CASINO_TOKEN_ID + 30,
    "CC - Casino Token 31": CC_ID + CASINO_TOKEN_ID + 31,
    "CC - Casino Token 32": CC_ID + CASINO_TOKEN_ID + 32,
    "CC - Casino Token 33": CC_ID + CASINO_TOKEN_ID + 33,
    "CC - Casino Token 34": CC_ID + CASINO_TOKEN_ID + 34,
    "CC - Casino Token 35": CC_ID + CASINO_TOKEN_ID + 35,
    "CC - Casino Token 36": CC_ID + CASINO_TOKEN_ID + 36,
    "CC - Casino Token 37": CC_ID + CASINO_TOKEN_ID + 37,
    "CC - Casino Token 38": CC_ID + CASINO_TOKEN_ID + 38,
    "CC - Casino Token 39": CC_ID + CASINO_TOKEN_ID + 39,
    "CC - Casino Token 40": CC_ID + CASINO_TOKEN_ID + 40,
    "CC - Casino Token 41": CC_ID + CASINO_TOKEN_ID + 41,
    "CC - Casino Token 42": CC_ID + CASINO_TOKEN_ID + 42,
    "CC - Casino Token 43": CC_ID + CASINO_TOKEN_ID + 43,
    "CC - Casino Token 44": CC_ID + CASINO_TOKEN_ID + 44,
    "CC - Casino Token 45": CC_ID + CASINO_TOKEN_ID + 45,
    "CC - Casino Token 46": CC_ID + CASINO_TOKEN_ID + 46,
    "CC - Casino Token 47": CC_ID + CASINO_TOKEN_ID + 47,
    "CC - Casino Token 48": CC_ID + CASINO_TOKEN_ID + 48,
    "CC - Casino Token 49": CC_ID + CASINO_TOKEN_ID + 49,
    "CC - Casino Token 50": CC_ID + CASINO_TOKEN_ID + 50,
    "CC - Casino Token 51": CC_ID + CASINO_TOKEN_ID + 51,
    "CC - Casino Token 52": CC_ID + CASINO_TOKEN_ID + 52,
    "CC - Casino Token 53": CC_ID + CASINO_TOKEN_ID + 53,
    "CC - Casino Token 54": CC_ID + CASINO_TOKEN_ID + 54,
    "CC - Casino Token 55": CC_ID + CASINO_TOKEN_ID + 55,
    "CC - Casino Token 56": CC_ID + CASINO_TOKEN_ID + 56,
    "CC - Casino Token 57": CC_ID + CASINO_TOKEN_ID + 57,
    "CC - Casino Token 58": CC_ID + CASINO_TOKEN_ID + 58,
    "CC - Casino Token 59": CC_ID + CASINO_TOKEN_ID + 59,
    "CC - Casino Token 60": CC_ID + CASINO_TOKEN_ID + 60,
    "CC - Casino Token 61": CC_ID + CASINO_TOKEN_ID + 61,
    "CC - Casino Token 62": CC_ID + CASINO_TOKEN_ID + 62,
    "CC - Casino Token 63": CC_ID + CASINO_TOKEN_ID + 63,
    "CC - Casino Token 64": CC_ID + CASINO_TOKEN_ID + 64,
    "CC - Casino Token 65": CC_ID + CASINO_TOKEN_ID + 65,
    "CC - Casino Token 66": CC_ID + CASINO_TOKEN_ID + 66,
    "CC - Casino Token 67": CC_ID + CASINO_TOKEN_ID + 67,
    "CC - Casino Token 68": CC_ID + CASINO_TOKEN_ID + 68,
    "CC - Casino Token 69": CC_ID + CASINO_TOKEN_ID + 69,
    "CC - Casino Token 70": CC_ID + CASINO_TOKEN_ID + 70,
    "CC - Casino Token 71": CC_ID + CASINO_TOKEN_ID + 71,
    "CC - Casino Token 72": CC_ID + CASINO_TOKEN_ID + 72,
    "CC - Casino Token 73": CC_ID + CASINO_TOKEN_ID + 73,
    "CC - Casino Token 74": CC_ID + CASINO_TOKEN_ID + 74,
    "CC - Casino Token 75": CC_ID + CASINO_TOKEN_ID + 75,
    "CC - Casino Token 76": CC_ID + CASINO_TOKEN_ID + 76,
    "CC - Casino Token 77": CC_ID + CASINO_TOKEN_ID + 77,
    "CC - Casino Token 78": CC_ID + CASINO_TOKEN_ID + 78,
    "CC - Casino Token 79": CC_ID + CASINO_TOKEN_ID + 79,
    "CC - Casino Token 80": CC_ID + CASINO_TOKEN_ID + 80,
    "CC - Casino Token 81": CC_ID + CASINO_TOKEN_ID + 81,
    "CC - Casino Token 82": CC_ID + CASINO_TOKEN_ID + 82,
    "CC - Casino Token 83": CC_ID + CASINO_TOKEN_ID + 83,
    "CC - Casino Token 84": CC_ID + CASINO_TOKEN_ID + 84,
    "CC - Casino Token 85": CC_ID + CASINO_TOKEN_ID + 85,
    "CC - Casino Token 86": CC_ID + CASINO_TOKEN_ID + 86,
    "CC - Casino Token 87": CC_ID + CASINO_TOKEN_ID + 87,
    "CC - Casino Token 88": CC_ID + CASINO_TOKEN_ID + 88,
    "CC - Casino Token 89": CC_ID + CASINO_TOKEN_ID + 89,
    "CC - Casino Token 90": CC_ID + CASINO_TOKEN_ID + 90,
    "CC - Casino Token 91": CC_ID + CASINO_TOKEN_ID + 91,
    "CC - Casino Token 92": CC_ID + CASINO_TOKEN_ID + 92,
    "CC - Casino Token 93": CC_ID + CASINO_TOKEN_ID + 93,
    "CC - Casino Token 94": CC_ID + CASINO_TOKEN_ID + 94,
    "CC - Casino Token 95": CC_ID + CASINO_TOKEN_ID + 95,
    "CC - Casino Token 96": CC_ID + CASINO_TOKEN_ID + 96,
    "CC - Casino Token 97": CC_ID + CASINO_TOKEN_ID + 97,
    "CC - Casino Token 98": CC_ID + CASINO_TOKEN_ID + 98,
    "CC - Casino Token 99": CC_ID + CASINO_TOKEN_ID + 99,
    "CC - Casino Token 100": CC_ID + CASINO_TOKEN_ID + 100,
    "CC - Casino Token 101": CC_ID + CASINO_TOKEN_ID + 101,
    "CC - Casino Token 102": CC_ID + CASINO_TOKEN_ID + 102,
    "CC - Casino Token 103": CC_ID + CASINO_TOKEN_ID + 103,
    "CC - Casino Token 104": CC_ID + CASINO_TOKEN_ID + 104,
    "CC - Casino Token 105": CC_ID + CASINO_TOKEN_ID + 105,
    "CC - Casino Token 106": CC_ID + CASINO_TOKEN_ID + 106,
    "CC - Casino Token 107": CC_ID + CASINO_TOKEN_ID + 107,
    "CC - Casino Token 108": CC_ID + CASINO_TOKEN_ID + 108,
    "CC - Casino Token 109": CC_ID + CASINO_TOKEN_ID + 109,
    "CC - Casino Token 110": CC_ID + CASINO_TOKEN_ID + 110,
    "CC - Casino Token 111": CC_ID + CASINO_TOKEN_ID + 111,
    "CC - Casino Token 112": CC_ID + CASINO_TOKEN_ID + 112,
    "CC - Casino Token 113": CC_ID + CASINO_TOKEN_ID + 113,
    "CC - Casino Token 114": CC_ID + CASINO_TOKEN_ID + 114,
    "CC - Casino Token 115": CC_ID + CASINO_TOKEN_ID + 115,
    "CC - Casino Token 116": CC_ID + CASINO_TOKEN_ID + 116,
    "CC - Casino Token 117": CC_ID + CASINO_TOKEN_ID + 117,
    "CC - Casino Token 118": CC_ID + CASINO_TOKEN_ID + 118,
    "CC - Casino Token 119": CC_ID + CASINO_TOKEN_ID + 119,
    "CC - Casino Token 120": CC_ID + CASINO_TOKEN_ID + 120,
    "CC - Casino Token 121": CC_ID + CASINO_TOKEN_ID + 121,
    "CC - Casino Token 122": CC_ID + CASINO_TOKEN_ID + 122,
    "CC - Casino Token 123": CC_ID + CASINO_TOKEN_ID + 123,
    "CC - Casino Token 124": CC_ID + CASINO_TOKEN_ID + 124,
    "CC - Casino Token 125": CC_ID + CASINO_TOKEN_ID + 125,
    "CC - Casino Token 126": CC_ID + CASINO_TOKEN_ID + 126,
    "CC - Casino Token 127": CC_ID + CASINO_TOKEN_ID + 127,
    "CC - Casino Token 128": CC_ID + CASINO_TOKEN_ID + 128,
    "CC - Casino Token 129": CC_ID + CASINO_TOKEN_ID + 129,
    "CC - Casino Token 130": CC_ID + CASINO_TOKEN_ID + 130,
    "CC - Casino Token 131": CC_ID + CASINO_TOKEN_ID + 131,
    "CC - Casino Token 132": CC_ID + CASINO_TOKEN_ID + 132,
    "CC - Casino Token 133": CC_ID + CASINO_TOKEN_ID + 133,
    "CC - Casino Token 134": CC_ID + CASINO_TOKEN_ID + 134,
    "CC - Casino Token 135": CC_ID + CASINO_TOKEN_ID + 135,
    "CC - Casino Token 136": CC_ID + CASINO_TOKEN_ID + 136,
    "CC - Casino Token 137": CC_ID + CASINO_TOKEN_ID + 137,
    "CC - Casino Token 138": CC_ID + CASINO_TOKEN_ID + 138,
    "CC - Casino Token 139": CC_ID + CASINO_TOKEN_ID + 139,
    "CC - Casino Token 140": CC_ID + CASINO_TOKEN_ID + 140,
    "CC - Casino Token 141": CC_ID + CASINO_TOKEN_ID + 141,
    "CC - Casino Token 142": CC_ID + CASINO_TOKEN_ID + 142,
    "CC - Casino Token 143": CC_ID + CASINO_TOKEN_ID + 143,
    "CC - Casino Token 144": CC_ID + CASINO_TOKEN_ID + 144,
    "CC - Casino Token 145": CC_ID + CASINO_TOKEN_ID + 145,
    "CC - Casino Token 146": CC_ID + CASINO_TOKEN_ID + 146,
    "CC - Casino Token 147": CC_ID + CASINO_TOKEN_ID + 147,
    "CC - Casino Token 148": CC_ID + CASINO_TOKEN_ID + 148,
    "CC - Casino Token 149": CC_ID + CASINO_TOKEN_ID + 149,
    "CC - Casino Token 150": CC_ID + CASINO_TOKEN_ID + 150,
    
    # Capital Cashino - Pagies
    # "CC - 5 Tokens Redeemed": CC_ID + PAGIE_ID + 0,
    # "CC - 10 Tokens Redeemed": CC_ID + PAGIE_ID + 1,
    # "CC - 15 Tokens Redeemed": CC_ID + PAGIE_ID + 2,
    # "CC - 20 Tokens Redeemed": CC_ID + PAGIE_ID + 3,
    # "CC - 25 Tokens Redeemed": CC_ID + PAGIE_ID + 4,
    # "CC - 30 Tokens Redeemed": CC_ID + PAGIE_ID + 5,
    # "CC - 35 Tokens Redeemed": CC_ID + PAGIE_ID + 6,
    # "CC - 40 Tokens Redeeemed": CC_ID + PAGIE_ID + 7,
    # "CC - 45 Tokens Redeemed": CC_ID + PAGIE_ID + 8,
    # "CC - 50 Tokens Redeemed": CC_ID + PAGIE_ID + 9,
    # "CC - 55 Tokens Redeeemed": CC_ID + PAGIE_ID + 10,
    # "CC - 60 Tokens Redeemed": CC_ID + PAGIE_ID + 11,
    # "CC - 65 Tokens Redeemed": CC_ID + PAGIE_ID + 12,
    # "CC - 70 Tokens Redeemed": CC_ID + PAGIE_ID + 13,
    # "CC - 75 Tokens Redeemed": CC_ID + PAGIE_ID + 14,
    # "CC - 80 Tokens Redeemed": CC_ID + PAGIE_ID + 15,
    # "CC - 85 Tokens Reedemed": CC_ID + PAGIE_ID + 16,
    # "CC - 90 Tokens Redeemed": CC_ID + PAGIE_ID + 17,
    # "CC - 95 Tokens Redeemed": CC_ID + PAGIE_ID + 18,
    # "CC - 100 Tokens Redeemed": CC_ID + PAGIE_ID + 19,
    # "CC - 105 Tokens Redeemed": CC_ID + PAGIE_ID + 20,
    # "CC - 110 Tokens Redeemed": CC_ID + PAGIE_ID + 21,
    # "CC - 115 Tokens Reedeemed": CC_ID + PAGIE_ID + 22,
    # "CC - 120 Tokens Redeemed": CC_ID + PAGIE_ID + 23,
    # "CC - 125 Tokens Redeemed": CC_ID + PAGIE_ID + 24,
    # "CC - 130 Tokens Redeemed": CC_ID + PAGIE_ID + 25,
    # "CC - 135 Tokens Redeemed": CC_ID + PAGIE_ID + 26,
    # "CC - 140 Tokens Redeemd": CC_ID + PAGIE_ID + 27,
    # "CC - 145 Tokens Redeemed": CC_ID + PAGIE_ID + 28,
    # "CC - 150 Tokens Redeemed": CC_ID + PAGIE_ID + 29,
    "CC - Kartos (Bronze)": CC_ID + PAGIE_ID + 30,
    "CC - Kartos (Silver)": CC_ID + PAGIE_ID + 31,
    "CC - Kartos (Gold)": CC_ID + PAGIE_ID + 32,
    "CC - Rextro (Bronze)": CC_ID + PAGIE_ID + 33,
    "CC - Rextro (Silver)": CC_ID + PAGIE_ID + 34,
    "CC - Rextro (Gold)": CC_ID + PAGIE_ID + 35,
    # "CC - 4 Pagie Pieces": CC_ID + PAGIE_ID + 36,
    # "CC - 4 More Pagie Pieces": CC_ID + PAGIE_ID + 37,
    "CC - Collect all the Quills": CC_ID + PAGIE_ID + 38,
    # "CC - Normy Nabbed": CC_ID + PAGIE_ID + 39,
    # "CC - Ann-Gree Acquired": CC_ID + PAGIE_ID + 40,
    # "CC - Heidi Handled": CC_ID + PAGIE_ID + 41,
    # "CC - Fee-Dee Found": CC_ID + PAGIE_ID + 42,
    # "CC - Evie Exorcised": CC_ID + PAGIE_ID + 43,
    "CC - Grand Tome Ghosts": CC_ID + PAGIE_ID + 44,
    "CC - I.N.E.P.T. Derailed": CC_ID + PAGIE_ID + 45,
    "CC - Pagie Piece 1": CC_ID + PAGIE_ID + 46,
    "CC - Pagie Piece 2": CC_ID + PAGIE_ID + 47,
    "CC - Pagie Piece 3": CC_ID + PAGIE_ID + 48,
    "CC - Pagie Piece 4": CC_ID + PAGIE_ID + 49,
    "CC - Pagie Piece 5": CC_ID + PAGIE_ID + 50,
    "CC - Pagie Piece 6": CC_ID + PAGIE_ID + 51,
    "CC - Pagie Piece 7": CC_ID + PAGIE_ID + 52,
    "CC - Pagie Piece 8": CC_ID + PAGIE_ID + 53,

    
        # Galleon Galaxy - Quills
    "GaGa - Quill 0": GA_ID + QUILL_ID + 0,
    "GaGa - Quill 1": GA_ID + QUILL_ID + 1,
    "GaGa - Quill 2": GA_ID + QUILL_ID + 2,
    "GaGa - Quill 3": GA_ID + QUILL_ID + 3,
    "GaGa - Quill 4": GA_ID + QUILL_ID + 4,
    "GaGa - Quill 5": GA_ID + QUILL_ID + 5,
    "GaGa - Quill 6": GA_ID + QUILL_ID + 6,
    "GaGa - Quill 7": GA_ID + QUILL_ID + 7,
    "GaGa - Quill 8": GA_ID + QUILL_ID + 8,
    "GaGa - Quill 9": GA_ID + QUILL_ID + 9,
    "GaGa - Quill 10": GA_ID + QUILL_ID + 10,
    "GaGa - Quill 11": GA_ID + QUILL_ID + 11,
    "GaGa - Quill 12": GA_ID + QUILL_ID + 12,
    "GaGa - Quill 13": GA_ID + QUILL_ID + 13,
    "GaGa - Quill 14": GA_ID + QUILL_ID + 14,
    "GaGa - Quill 15": GA_ID + QUILL_ID + 15,
    "GaGa - Quill 16": GA_ID + QUILL_ID + 16,
    "GaGa - Quill 17": GA_ID + QUILL_ID + 17,
    "GaGa - Quill 18": GA_ID + QUILL_ID + 18,
    "GaGa - Quill 19": GA_ID + QUILL_ID + 19,
    "GaGa - Quill 20": GA_ID + QUILL_ID + 20,
    "GaGa - Quill 21": GA_ID + QUILL_ID + 21,
    "GaGa - Quill 22": GA_ID + QUILL_ID + 22,
    "GaGa - Quill 23": GA_ID + QUILL_ID + 23,
    "GaGa - Quill 24": GA_ID + QUILL_ID + 24,
    "GaGa - Quill 25": GA_ID + QUILL_ID + 25,
    "GaGa - Quill 26": GA_ID + QUILL_ID + 26,
    "GaGa - Quill 27": GA_ID + QUILL_ID + 27,
    "GaGa - Quill 28": GA_ID + QUILL_ID + 28,
    "GaGa - Quill 29": GA_ID + QUILL_ID + 29,
    "GaGa - Quill 30": GA_ID + QUILL_ID + 30,
    "GaGa - Quill 31": GA_ID + QUILL_ID + 31,
    "GaGa - Quill 32": GA_ID + QUILL_ID + 32,
    "GaGa - Quill 33": GA_ID + QUILL_ID + 33,
    "GaGa - Quill 34": GA_ID + QUILL_ID + 34,
    "GaGa - Quill 35": GA_ID + QUILL_ID + 35,
    "GaGa - Quill 36": GA_ID + QUILL_ID + 36,
    "GaGa - Quill 37": GA_ID + QUILL_ID + 37,
    "GaGa - Quill 38": GA_ID + QUILL_ID + 38,
    "GaGa - Quill 39": GA_ID + QUILL_ID + 39,
    "GaGa - Quill 40": GA_ID + QUILL_ID + 40,
    "GaGa - Quill 41": GA_ID + QUILL_ID + 41,
    "GaGa - Quill 42": GA_ID + QUILL_ID + 42,
    "GaGa - Quill 43": GA_ID + QUILL_ID + 43,
    "GaGa - Quill 44": GA_ID + QUILL_ID + 44,
    "GaGa - Quill 45": GA_ID + QUILL_ID + 45,
    "GaGa - Quill 46": GA_ID + QUILL_ID + 46,
    "GaGa - Quill 47": GA_ID + QUILL_ID + 47,
    "GaGa - Quill 48": GA_ID + QUILL_ID + 48,
    "GaGa - Quill 49": GA_ID + QUILL_ID + 49,
    "GaGa - Quill 50": GA_ID + QUILL_ID + 50,
    "GaGa - Quill 51": GA_ID + QUILL_ID + 51,
    "GaGa - Quill 52": GA_ID + QUILL_ID + 52,
    "GaGa - Quill 53": GA_ID + QUILL_ID + 53,
    "GaGa - Quill 54": GA_ID + QUILL_ID + 54,
    "GaGa - Quill 55": GA_ID + QUILL_ID + 55,
    "GaGa - Quill 56": GA_ID + QUILL_ID + 56,
    "GaGa - Quill 57": GA_ID + QUILL_ID + 57,
    "GaGa - Quill 58": GA_ID + QUILL_ID + 58,
    "GaGa - Quill 59": GA_ID + QUILL_ID + 59,
    "GaGa - Quill 60": GA_ID + QUILL_ID + 60,
    "GaGa - Quill 61": GA_ID + QUILL_ID + 61,
    "GaGa - Quill 62": GA_ID + QUILL_ID + 62,
    "GaGa - Quill 63": GA_ID + QUILL_ID + 63,
    "GaGa - Quill 64": GA_ID + QUILL_ID + 64,
    "GaGa - Quill 65": GA_ID + QUILL_ID + 65,
    "GaGa - Quill 66": GA_ID + QUILL_ID + 66,
    "GaGa - Quill 67": GA_ID + QUILL_ID + 67,
    "GaGa - Quill 68": GA_ID + QUILL_ID + 68,
    "GaGa - Quill 69": GA_ID + QUILL_ID + 69,
    "GaGa - Quill 70": GA_ID + QUILL_ID + 70,
    "GaGa - Quill 71": GA_ID + QUILL_ID + 71,
    "GaGa - Quill 72": GA_ID + QUILL_ID + 72,
    "GaGa - Quill 73": GA_ID + QUILL_ID + 73,
    "GaGa - Quill 74": GA_ID + QUILL_ID + 74,
    "GaGa - Quill 75": GA_ID + QUILL_ID + 75,
    "GaGa - Quill 76": GA_ID + QUILL_ID + 76,
    "GaGa - Quill 77": GA_ID + QUILL_ID + 77,
    "GaGa - Quill 78": GA_ID + QUILL_ID + 78,
    "GaGa - Quill 79": GA_ID + QUILL_ID + 79,
    "GaGa - Quill 80": GA_ID + QUILL_ID + 80,
    "GaGa - Quill 81": GA_ID + QUILL_ID + 81,
    "GaGa - Quill 82": GA_ID + QUILL_ID + 82,
    "GaGa - Quill 83": GA_ID + QUILL_ID + 83,
    "GaGa - Quill 84": GA_ID + QUILL_ID + 84,
    "GaGa - Quill 85": GA_ID + QUILL_ID + 85,
    "GaGa - Quill 86": GA_ID + QUILL_ID + 86,
    "GaGa - Quill 87": GA_ID + QUILL_ID + 87,
    "GaGa - Quill 88": GA_ID + QUILL_ID + 88,
    "GaGa - Quill 89": GA_ID + QUILL_ID + 89,
    "GaGa - Quill 90": GA_ID + QUILL_ID + 90,
    "GaGa - Quill 91": GA_ID + QUILL_ID + 91,
    "GaGa - Quill 92": GA_ID + QUILL_ID + 92,
    "GaGa - Quill 93": GA_ID + QUILL_ID + 93,
    "GaGa - Quill 94": GA_ID + QUILL_ID + 94,
    "GaGa - Quill 95": GA_ID + QUILL_ID + 95,
    "GaGa - Quill 96": GA_ID + QUILL_ID + 96,
    "GaGa - Quill 97": GA_ID + QUILL_ID + 97,
    "GaGa - Quill 98": GA_ID + QUILL_ID + 98,
    "GaGa - Quill 99": GA_ID + QUILL_ID + 99,
    "GaGa - Quill 100": GA_ID + QUILL_ID + 100,
    "GaGa - Quill 101": GA_ID + QUILL_ID + 101,
    "GaGa - Quill 102": GA_ID + QUILL_ID + 102,
    "GaGa - Quill 103": GA_ID + QUILL_ID + 103,
    "GaGa - Quill 104": GA_ID + QUILL_ID + 104,
    "GaGa - Quill 105": GA_ID + QUILL_ID + 105,
    "GaGa - Quill 106": GA_ID + QUILL_ID + 106,
    "GaGa - Quill 107": GA_ID + QUILL_ID + 107,
    "GaGa - Quill 108": GA_ID + QUILL_ID + 108,
    "GaGa - Quill 109": GA_ID + QUILL_ID + 109,
    "GaGa - Quill 110": GA_ID + QUILL_ID + 110,
    "GaGa - Quill 111": GA_ID + QUILL_ID + 111,
    "GaGa - Quill 112": GA_ID + QUILL_ID + 112,
    "GaGa - Quill 113": GA_ID + QUILL_ID + 113,
    "GaGa - Quill 114": GA_ID + QUILL_ID + 114,
    "GaGa - Quill 115": GA_ID + QUILL_ID + 115,
    "GaGa - Quill 116": GA_ID + QUILL_ID + 116,
    "GaGa - Quill 117": GA_ID + QUILL_ID + 117,
    "GaGa - Quill 118": GA_ID + QUILL_ID + 118,
    "GaGa - Quill 119": GA_ID + QUILL_ID + 119,
    "GaGa - Quill 120": GA_ID + QUILL_ID + 120,
    "GaGa - Quill 121": GA_ID + QUILL_ID + 121,
    "GaGa - Quill 122": GA_ID + QUILL_ID + 122,
    "GaGa - Quill 123": GA_ID + QUILL_ID + 123,
    "GaGa - Quill 124": GA_ID + QUILL_ID + 124,
    "GaGa - Quill 125": GA_ID + QUILL_ID + 125,
    "GaGa - Quill 126": GA_ID + QUILL_ID + 126,
    "GaGa - Quill 127": GA_ID + QUILL_ID + 127,
    "GaGa - Quill 128": GA_ID + QUILL_ID + 128,
    "GaGa - Quill 129": GA_ID + QUILL_ID + 129,
    "GaGa - Quill 130": GA_ID + QUILL_ID + 130,
    "GaGa - Quill 131": GA_ID + QUILL_ID + 131,
    "GaGa - Quill 132": GA_ID + QUILL_ID + 132,
    "GaGa - Quill 133": GA_ID + QUILL_ID + 133,
    "GaGa - Quill 134": GA_ID + QUILL_ID + 134,
    "GaGa - Quill 135": GA_ID + QUILL_ID + 135,
    "GaGa - Quill 136": GA_ID + QUILL_ID + 136,
    "GaGa - Quill 137": GA_ID + QUILL_ID + 137,
    "GaGa - Quill 138": GA_ID + QUILL_ID + 138,
    "GaGa - Quill 139": GA_ID + QUILL_ID + 139,
    "GaGa - Quill 140": GA_ID + QUILL_ID + 140,
    "GaGa - Quill 141": GA_ID + QUILL_ID + 141,
    "GaGa - Quill 142": GA_ID + QUILL_ID + 142,
    "GaGa - Quill 143": GA_ID + QUILL_ID + 143,
    "GaGa - Quill 144": GA_ID + QUILL_ID + 144,
    "GaGa - Quill 145": GA_ID + QUILL_ID + 145,
    "GaGa - Quill 146": GA_ID + QUILL_ID + 146,
    "GaGa - Quill 147": GA_ID + QUILL_ID + 147,
    "GaGa - Quill 148": GA_ID + QUILL_ID + 148,
    "GaGa - Quill 149": GA_ID + QUILL_ID + 149,
    
       # Galleon Galaxy - Pagies
    "GaGa - Calcified Castaway": GA_ID + PAGIE_ID + 0,
    # "GaGa - Ann-Gree Acquired": GA_ID + PAGIE_ID + 1,
    # "GaGa - Fee-Dee Found": GA_ID + PAGIE_ID + 2,
    # "GaGa - Evie Exorcised": GA_ID + PAGIE_ID + 3,
    # "GaGa - Heidi Handled": GA_ID + PAGIE_ID + 4,
    # "GaGa - Normy Nabbed": GA_ID + PAGIE_ID + 5,
    "GaGa - Grand Tome Ghosts": GA_ID + PAGIE_ID + 6,
    "GaGa - A Race in Space": GA_ID + PAGIE_ID + 7,
    "GaGa - Galactic Gold": GA_ID + PAGIE_ID + 8,
    "GaGa - Tidal Targets": GA_ID + PAGIE_ID + 9,
    "GaGa - Galactic Golfing": GA_ID + PAGIE_ID + 10,
    "GaGa - Ramped Up Rock": GA_ID + PAGIE_ID + 11,
    "GaGa - Lightspeed Clamber": GA_ID + PAGIE_ID + 12,
    "GaGa - Return Orbit": GA_ID + PAGIE_ID + 13,
    "GaGa - Unstable Station": GA_ID + PAGIE_ID + 14,
    "GaGa - Fish in a Barrel": GA_ID + PAGIE_ID + 15,
    "GaGa - Defrost Flight": GA_ID + PAGIE_ID + 16,
    "GaGa - Balloon Bust": GA_ID + PAGIE_ID + 17,
    "GaGa - Strongman Slam": GA_ID + PAGIE_ID + 18,
    "GaGa - Island Hoop Hop": GA_ID + PAGIE_ID + 19,
    "GaGa - Castaway Treasure": GA_ID + PAGIE_ID + 20,
    "GaGa - Piggy Bank Yank": GA_ID + PAGIE_ID + 21,
    "GaGa - Rextro (Bronze)": GA_ID + PAGIE_ID + 22,
    "GaGa - Rextro (Silver)": GA_ID + PAGIE_ID + 23,
    "GaGa - Rextro (Gold)": GA_ID + PAGIE_ID + 24,
    "GaGa - Kartos (Bronze)": GA_ID + PAGIE_ID + 25,
    "GaGa - Kartos (Silver)": GA_ID + PAGIE_ID + 26,
    "GaGa - Kartos (Gold)": GA_ID + PAGIE_ID + 27,
    "GaGa - Collect all the Quills": GA_ID + PAGIE_ID + 28,
    # "GaGa - 4 Pagie Pieces": GA_ID + PAGIE_ID + 29,
    # "GaGa - 4 More Pagie Pieces": GA_ID + PAGIE_ID + 30,
    "GaGa - Gravity Grab": GA_ID + PAGIE_ID + 31,
    "GaGa - Cowardly Captain": GA_ID + PAGIE_ID + 32,
    "GaGa - Shipshape": GA_ID + PAGIE_ID + 33,
    "GaGa - Robot Robbery": GA_ID + PAGIE_ID + 34,
    "GaGa - Anti-gravity Antics": GA_ID + PAGIE_ID + 35,
    "GaGa - Superspeed Slide": GA_ID + PAGIE_ID + 36,
    "GaGa - Superspeed Special": GA_ID + PAGIE_ID + 37,
    "GaGa - Star Fishing": GA_ID + PAGIE_ID + 38,
    "GaGa - Star Fish Flash": GA_ID + PAGIE_ID + 39,
    "GaGa - Charged Up Colossus": GA_ID + PAGIE_ID + 40,
    "GaGa - Schell Game": GA_ID + PAGIE_ID + 41,
    "GaGa - Raising Schell": GA_ID + PAGIE_ID + 42,
    "GaGa - Toilet Trouble": GA_ID + PAGIE_ID + 43,
    "GaGa - Shockball Shuffle": GA_ID + PAGIE_ID + 44,
    "GaGa - Malicious Moon": GA_ID + PAGIE_ID + 45,
    "GaGa - Pagie Piece 1": GA_ID + PAGIE_ID + 46,
    "GaGa - Pagie Piece 2": GA_ID + PAGIE_ID + 47,
    "GaGa - Pagie Piece 3": GA_ID + PAGIE_ID + 48,
    "GaGa - Pagie Piece 4": GA_ID + PAGIE_ID + 49,
    "GaGa - Pagie Piece 5": GA_ID + PAGIE_ID + 50,
    "GaGa - Pagie Piece 6": GA_ID + PAGIE_ID + 51,
    "GaGa - Pagie Piece 7": GA_ID + PAGIE_ID + 52,
    "GaGa - Pagie Piece 8": GA_ID + PAGIE_ID + 53,



    # Trowzer Shops - enabled only with Quillsanity
    "TT - Shop 1": TT_ID + SHOP_ID + 0,
    "TT - Shop 2": TT_ID + SHOP_ID + 1,
    "TT - Shop 3": TT_ID + SHOP_ID + 2,
    "TT - Shop 4": TT_ID + SHOP_ID + 3,
    "TT - Shop 5": TT_ID + SHOP_ID + 4,
    "TT - Shop 6": TT_ID + SHOP_ID + 5,
    "GlGl - Shop 1": GL_ID + SHOP_ID + 0,
    "GlGl - Shop 2": GL_ID + SHOP_ID + 1,
    "GlGl - Shop 3": GL_ID + SHOP_ID + 2,
    "GlGl - Shop 4": GL_ID + SHOP_ID + 3,
    "GlGl - Shop 5": GL_ID + SHOP_ID + 4,
    "GlGl - Shop 6": GL_ID + SHOP_ID + 5,
    "MM - Shop 1": MM_ID + SHOP_ID + 0,
    "MM - Shop 2": MM_ID + SHOP_ID + 1,
    "MM - Shop 3": MM_ID + SHOP_ID + 2,
    "MM - Shop 4": MM_ID + SHOP_ID + 3,
    "MM - Shop 5": MM_ID + SHOP_ID + 4,
    "MM - Shop 6": MM_ID + SHOP_ID + 5,
    "CC - Shop 1": CC_ID + SHOP_ID + 0,
    "CC - Shop 2": CC_ID + SHOP_ID + 1,
    "CC - Shop 3": CC_ID + SHOP_ID + 2,
    "CC - Shop 4": CC_ID + SHOP_ID + 3,
    "CC - Shop 5": CC_ID + SHOP_ID + 4,
    "CC - Shop 6": CC_ID + SHOP_ID + 5,
    "GaGa - Shop 1": GA_ID + SHOP_ID + 0,
    "GaGa - Shop 2": GA_ID + SHOP_ID + 1,
    "GaGa - Shop 3": GA_ID + SHOP_ID + 2,
    "GaGa - Shop 4": GA_ID + SHOP_ID + 3,
    "GaGa - Shop 5": GA_ID + SHOP_ID + 4,
    "GaGa - Shop 6": GA_ID + SHOP_ID + 5,
}

class YookaReplayleeLocation(Location):
    game = "Yooka-Replaylee"


def create_all_locations(world: ReplayleeWorld) -> None:
    create_regular_locations(world)
    if world.options.goal.value == 0:  # triple_pagie_medal_hunt
        create_triple_pagie_medal_rewards(world)
    elif world.options.goal.value == 2:  # defeat_capital_b
        world.get_location("HT - Capital Beaten").place_locked_item(world.create_item("Victory"))


def create_triple_pagie_medal_rewards(world: ReplayleeWorld) -> None:
    """Lock a Triple Pagie Medal to every location that awards one.

    These are real Archipelago locations (with IDs), so completing them
    sends a normal AP item rather than a generation-only event.
    """

    required_locations = {
        "TT - Rampo's Rampagie",
        "GlGl - Brrreeze Blocked",
        "MM - Tentacle Test",
        "CC - I.N.E.P.T. Derailed",
        "GaGa - Malicious Moon",
    }

    required_locations.update(
        name for name in LOCATION_NAME_TO_ID
        if "Grand Tome Ghosts" in name
    )

    for location_name in required_locations:
        location = world.get_location(location_name)
        location.place_locked_item(
            world.create_item("Triple Pagie Medal")
        )


def create_regular_locations(world: ReplayleeWorld) -> None:
    ht_entrance = world.get_region("Hivory Towers Entrance")
    tt_entrance = world.get_region("Tribalstack Tropics Entrance")
    gl_entrance = world.get_region("Glitterglaze Glacier Entrance")
    mm_entrance = world.get_region("Moodymaze Marsh Entrance")
    cc_entrance = world.get_region("Capital Cashino Entrance")
    ga_entrance = world.get_region("Galleon Galaxy Entrance")
    ht_hub_b = world.get_region("Hivory Towers Bypass 15 Door")
    ht_hub_b_2 = world.get_region("Hivory Towers Bypass 35 Door")
    ht_hub_c = world.get_region("Hivory Towers Bypass 55 Door")

    # Keep the complete location table intact. Quillsanity controls which
    # locations are instantiated into this seed.
    active_locations = {
        name: location_id
        for name, location_id in LOCATION_NAME_TO_ID.items()
        if (world.options.quillsanity.value or ("Quill" not in name and " - Shop " not in name))
        and (name != "HT - Capital Beaten" or world.options.goal.value == 2)
    }

    ht_hub_b_2_locations = {
        name: location_id
        for name, location_id in active_locations.items()
        if name.startswith("HT - ")
        and 10 <= location_id - (HT_ID + PAGIE_ID) <= 14
    }
    ht_hub_b_locations = {
        name: location_id
        for name, location_id in active_locations.items()
        if name.startswith("HT - ")
        and 15 <= location_id - (HT_ID + PAGIE_ID) <= 34
    }
    ht_hub_c_locations = {
        name: location_id
        for name, location_id in active_locations.items()
        if name.startswith("HT - ")
        and 35 <= location_id - (HT_ID + PAGIE_ID) <= 47
    }
    ht_locations = {
        name: location_id
        for name, location_id in active_locations.items()
        if name.startswith("HT - ")
        and 0 <= location_id - (HT_ID + PAGIE_ID) <= 9
    }
    tt_locations = {
        name: location_id for name, location_id in active_locations.items()
        if name.startswith("TT - ")
    }
    gl_locations = {
        name: location_id for name, location_id in active_locations.items()
        if name.startswith("GlGl - ") or name.startswith("GG - ")
    }
    mm_locations = {
        name: location_id for name, location_id in active_locations.items()
        if name.startswith("MM - ")
    }
    cc_locations = {
        name: location_id for name, location_id in active_locations.items()
        if name.startswith("CC - ")
    }
    ga_locations = {
        name: location_id for name, location_id in active_locations.items()
        if name.startswith("GaGa - ")
    }

    ht_entrance.add_locations(ht_locations, YookaReplayleeLocation)
    ht_hub_b.add_locations(ht_hub_b_locations, YookaReplayleeLocation)
    ht_hub_b_2.add_locations(ht_hub_b_2_locations, YookaReplayleeLocation)
    ht_hub_c.add_locations(ht_hub_c_locations, YookaReplayleeLocation)
    tt_entrance.add_locations(tt_locations, YookaReplayleeLocation)
    gl_entrance.add_locations(gl_locations, YookaReplayleeLocation)
    mm_entrance.add_locations(mm_locations, YookaReplayleeLocation)
    cc_entrance.add_locations(cc_locations, YookaReplayleeLocation)
    ga_entrance.add_locations(ga_locations, YookaReplayleeLocation)
